### ISSUE TITLE
[bug] break-changes in v0.2.8 - Getting Started

### ISSUE THREAD

**Issue by jccamargo94** [ktafakkori/feloopy#10]
## Summary
`feloopy` 0.2.8 just crashes with the minimal reproducible example available at [User Guide Example](https://feloopy.readthedocs.io/en/latest/#example). Almost all examples availables at docs are crashed

## Steps to reproduce the issue
1. Install feloopy: `pip install "feloopy[stock]"==0.2.8`
2. Reproduce the User Guide Example:
```
import feloopy as flp

m = flp.model("exact", "model_name", "pymprog")

x = m.bvar(name="x")
y = m.pvar(name="y", bound=[0, 1])
m.con(x + y <= 1, name="c1")
m.con(x - y >= 1, name="c2")
m.obj(x + y)

m.sol(["max"], "glpk")

m.report()
```

## Error Message
`Model.con() got an unexpected keyword argument 'name'`

## System information
feloopy version: `feloopy[stock] == 0.2.8`
Python version: Python 3.11.2
Operating system: Ubuntu 22.04.4 LTS
environment created with: anaconda 23.7.4
How feloopy was installed (PyPI, conda, source): pypi

**Comment by ktafakkori** [comment]
Thank you for the report and interest in using `feloopy`! The new version renames some arguments for consistency. To get the results, you may change `name=` to `label=` inside the `m.con()` command. Notably, examples are updated to match the upcoming release.
